const a = {
  data: [
    {
      id: 1,
      attributes: {
        createdAt: "2023-01-09T15:29:08.430Z",
        updatedAt: "2023-01-09T15:53:17.884Z",
        publishedAt: "2023-01-09T15:29:09.234Z",
        image: {
          data: {
            id: 1,
            attributes: {
              name: "hero-img.webp",
              alternativeText: null,
              caption: null,
              width: 2000,
              height: 2000,
              formats: {
                thumbnail: {
                  name: "thumbnail_vector-isolated-animal-silhouette-icon-simple-black-cat-shape-kitty-graphic-illustration-abstract-symbol-sign-design-element-vet-clinic-logo-pet-portrait-shadow-flat-style_550143-1091.webp",
                  hash: "thumbnail_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea",
                  ext: ".webp",
                  mime: "image/webp",
                  path: null,
                  width: 156,
                  height: 156,
                  size: 1.12,
                  url: "/uploads/thumbnail_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea.webp",
                },
                large: {
                  name: "large_vector-isolated-animal-silhouette-icon-simple-black-cat-shape-kitty-graphic-illustration-abstract-symbol-sign-design-element-vet-clinic-logo-pet-portrait-shadow-flat-style_550143-1091.webp",
                  hash: "large_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea",
                  ext: ".webp",
                  mime: "image/webp",
                  path: null,
                  width: 1000,
                  height: 1000,
                  size: 9.01,
                  url: "/uploads/large_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea.webp",
                },
                small: {
                  name: "small_vector-isolated-animal-silhouette-icon-simple-black-cat-shape-kitty-graphic-illustration-abstract-symbol-sign-design-element-vet-clinic-logo-pet-portrait-shadow-flat-style_550143-1091.webp",
                  hash: "small_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea",
                  ext: ".webp",
                  mime: "image/webp",
                  path: null,
                  width: 500,
                  height: 500,
                  size: 4.07,
                  url: "/uploads/small_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea.webp",
                },
                medium: {
                  name: "medium_vector-isolated-animal-silhouette-icon-simple-black-cat-shape-kitty-graphic-illustration-abstract-symbol-sign-design-element-vet-clinic-logo-pet-portrait-shadow-flat-style_550143-1091.webp",
                  hash: "medium_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea",
                  ext: ".webp",
                  mime: "image/webp",
                  path: null,
                  width: 750,
                  height: 750,
                  size: 6.29,
                  url: "/uploads/medium_vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea.webp",
                },
              },
              hash: "vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea",
              ext: ".webp",
              mime: "image/webp",
              size: 21.95,
              url: "/uploads/vector_isolated_animal_silhouette_icon_simple_black_cat_shape_kitty_graphic_illustration_abstract_symbol_sign_design_element_vet_clinic_logo_pet_portrait_shadow_flat_style_550143_1091_d5064994ea.webp",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-01-09T15:29:03.390Z",
              updatedAt: "2023-01-09T15:53:15.827Z",
            },
          },
        },
      },
    },
  ],
  meta: { pagination: { page: 1, pageSize: 25, pageCount: 1, total: 1 } },
};
